### ISSUE TITLE
load scene browser remains open after scene is loaded

### ISSUE THREAD

**Issue by df-0** [nvrmind/IssueTracker#18] opened 2018-01-19 12:38 UTC
when you load a scene [from the floating menu, running on oculus/windows 10]  the load scene browser remains open, probably shouldn't?

**Comment by daseyb** [comment] 2018-01-19 12:58
This is by design right now (the logic is that you might want to flip through stages and find the one you're looking for)
In this case, I think it staying open and you having to press the menu button to close it when you want to load one stage is less annoying than having to reopen it every time when you're looking through multiple stages.

**Comment by df-0** [comment] 2018-01-19 13:11
Ah, thought that might be the case. It's definitely fiddly translating non-vr ui into vr, none of the 'windows' stuff really makes sense any more. Yeah, felt a bit weird but I don't have a better suggestion!On 19 Jan 2018 12:59, Dario Seyb <notifications@github.com> wrote:This is by design right now (the logic is that you might want to flip through stages and find the one you're looking for)
In this case, I think it staying open and you having to press the menu button to close it when you want to load one stage is less annoying than having to reopen it every time when you're looking through multiple stages.

**Comment by daseyb** [comment] 2018-01-19 13:14
I'll close this issue for now. Feel free to reopen it if you notice that it keeps being super annoying!

**Closed as completed by daseyb** 2018-01-19 13:14 UTC

**Comment by df-0** [comment] 2018-01-19 13:22
Cool, fine with me!On 19 Jan 2018 13:14, Dario Seyb <notifications@github.com> wrote:I'll close this issue for now. Feel free to reopen it if you notice that it keeps being super annoying!
